### PR TITLE
Copied mapcubed module from ehsteve's sunpy PR

### PR DESCRIPTION
**Pull request by DanRyanIrish**
Copied mapcubed module from ehsteve's sunpy PR so we can start work with it while the PR is being finished and merged into sunpy.

### CODE REVIEW

**Comment by abit2** [comment]
@DanRyanIrish can you please merge this so I can start working on SJIMapSequence

**Comment by DanRyanIrish** [comment]
@abit2, yes I'll merge this today.  However, I would advise when working on SJIMapSequence to, as much as is possible, develop an abstract API to minimise how dependent we are on the specifics of MapCubed.  In light of the disagreements in riot last week, it is possible that we may want to use something other than MapCubed in the future if a better data cube object is developed in sunpy or astropy etc.  MapCubed is also bound to change before and after it is merged in sunpy.  So an abstract API will help minimise additional work for SJIMapSequence in the long run.

**Comment by Cadair** [comment]
I maintain this was not the right way to go...

**Comment by DanRyanIrish** [comment]
@Cadair, what do you suggest that we can use now to start developing API?

**Comment by Cadair** [comment]
From my limited knowledge of the data I think that sunpy/cube is a closer fit to what you need.

**Comment by DanRyanIrish** [comment]
So what's the point of MapCubed then?  As far as I know there isn't anything inherently different between AIA images and SJI images.  They are directly focused images of the Sun in EUV/UV.  Why would IRIS SJI need something inherently different than AIA?

**Comment by Cadair** [comment]
> So what's the point of MapCubed then?

I am not really sure on this you would have to ask @ehsteve. As written MapCubed is a collection of 2D headers and one contiguous 3D array.

> Why would IRIS SJI need something inherently different than AIA?

AIA images are a collection of 2D images and metadata, whereas SJI is one 3D array and a singular 3D header. sunpy/cube was written specifically to address the case of a 3D (or more) array with a single corresponding header.

Again, all of this is as MapCubed is currently implemented. Although, I don't see the point in re-implementing something that looks a lot like sunpy/cube.

**Comment by DanRyanIrish** [comment]
OK.  Thanks for the summary @Cadair.  You have a good point.

**Pull request merged**
