### PR TITLE
fix the docs for sunpy 0.9

### PR DESCRIPTION
**Pull request by Cadair**

### CODE REVIEW

**Comment by DanRyanIrish** [comment]
What is this doing and why is it required?

**Comment by Cadair** [comment]
it updates irispy to reflect changes in the sphinx theme, so that the header bar of irispy matches all the other sunpy pages.

**Comment by DanRyanIrish** [comment]
Could this be the cause of some of those weird errors we were discussing earlier?

**Comment by Cadair** [comment]
well the docs build passed.

**Comment by DanRyanIrish** [comment]
That was IRISpy.

**Pull request merged**
